name: Integration Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run integration tests
        run: make test-integration
